import {
  AlertTriangle, ArrowLeft, ArrowRight, ArrowUpRight,
  BarChart2, BookOpen, Brackets, BrainCircuit, Bug,
  Calendar, CalendarDays, Check, CheckCircle2, CheckSquare,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  Circle, ClipboardCopy, Cloud, CloudOff, Code2, Columns2, Copy,
  CornerDownLeft, Crosshair, Download, ExternalLink, Eye,
  FileDown, FileJson, FileText, FlaskConical,
  Folder, FolderInput, FolderOpen, FolderPlus, FolderSync,
  GitFork, GitMerge, Globe, GraduationCap, GripVertical,
  History, Home, Image, Info, Keyboard, Layers, LayoutDashboard, LayoutList,
  Lightbulb, Link, Link2, List, Loader2, MoreHorizontal,
  Network, Palette, PanelLeftClose, PanelLeftOpen, Pencil, Pin, Plus, Puzzle,
  Redo2, RefreshCw, RotateCcw, Save, ScrollText, Search,
  Send, Settings, Settings2, ShieldCheck, SquareKanban,
  StickyNote, Store, Tag, Trash2, Undo2, Unlink,
  Users, WifiOff, X, Zap,
} from 'lucide-react'
import type { IconPack } from './tokens'

export const builtinPack: IconPack = {
  'alert-triangle':  AlertTriangle,
  'arrow-left':      ArrowLeft,
  'arrow-right':     ArrowRight,
  'arrow-up-right':  ArrowUpRight,
  'bar-chart-2':     BarChart2,
  'book-open':       BookOpen,
  'brackets':        Brackets,
  'brain-circuit':   BrainCircuit,
  'bug':             Bug,
  'calendar':        Calendar,
  'calendar-days':   CalendarDays,
  'check':           Check,
  'check-circle-2':  CheckCircle2,
  'check-square':    CheckSquare,
  'chevron-down':    ChevronDown,
  'chevron-left':    ChevronLeft,
  'chevron-right':   ChevronRight,
  'chevron-up':      ChevronUp,
  'circle':          Circle,
  'clipboard-copy':  ClipboardCopy,
  'columns-2':       Columns2,
  'cloud':           Cloud,
  'cloud-off':       CloudOff,
  'code-2':          Code2,
  'copy':            Copy,
  'corner-down-left': CornerDownLeft,
  'crosshair':       Crosshair,
  'download':        Download,
  'external-link':   ExternalLink,
  'eye':             Eye,
  'file-down':       FileDown,
  'file-json':       FileJson,
  'file-text':       FileText,
  'flask-conical':   FlaskConical,
  'folder':          Folder,
  'folder-input':    FolderInput,
  'folder-open':     FolderOpen,
  'folder-plus':     FolderPlus,
  'folder-sync':     FolderSync,
  'git-fork':        GitFork,
  'git-merge':       GitMerge,
  'globe':           Globe,
  'graduation-cap':  GraduationCap,
  'grip-vertical':   GripVertical,
  'history':         History,
  'home':            Home,
  'image':           Image,
  'info':            Info,
  'keyboard':        Keyboard,
  'layers':             Layers,
  'layout-dashboard':   LayoutDashboard,
  'layout-list':        LayoutList,
  'lightbulb':       Lightbulb,
  'link':            Link,
  'link-2':          Link2,
  'list':            List,
  'loader-2':        Loader2,
  'more-horizontal': MoreHorizontal,
  'network':         Network,
  'palette':            Palette,
  'panel-left-close':   PanelLeftClose,
  'panel-left-open':    PanelLeftOpen,
  'pencil':             Pencil,
  'pin':             Pin,
  'plus':            Plus,
  'puzzle':          Puzzle,
  'redo-2':          Redo2,
  'refresh-cw':      RefreshCw,
  'rotate-ccw':      RotateCcw,
  'save':            Save,
  'scroll-text':     ScrollText,
  'search':          Search,
  'send':            Send,
  'settings':        Settings,
  'settings-2':      Settings2,
  'shield-check':    ShieldCheck,
  'square-kanban':   SquareKanban,
  'sticky-note':     StickyNote,
  'store':           Store,
  'tag':             Tag,
  'trash-2':         Trash2,
  'undo-2':          Undo2,
  'unlink':          Unlink,
  'users':           Users,
  'wifi-off':        WifiOff,
  'x':               X,
  'zap':             Zap,
}
