import {
  AlertTriangle, ArrowLeft, ArrowRight, ArrowUpRight,
  BarChart2, Bold, BookOpen, Bookmark, Brackets, BrainCircuit, Bug,
  Calendar, CalendarDays, Check, CheckCircle2, CheckSquare,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  Circle, ClipboardCopy, Cloud, CloudOff, Code2, Columns2, Copy,
  CornerDownLeft, Crosshair, Download, ExternalLink, Eye,
  FileDown, FileJson, FileText, FlaskConical,
  Folder, FolderInput, FolderOpen, FolderPlus, FolderSync,
  GitFork, GitMerge, Globe, GraduationCap, GripVertical,
  Hash, Heading1, Heading2, History, Home, Image, Film, Music, Paperclip, Info, Italic, Keyboard, Layers, LayoutDashboard, LayoutList,
  Lightbulb, Link, Link2, List, ListChecks, ListOrdered, Loader2, Lock, LockOpen, MoreHorizontal, Quote,
  Strikethrough,
  HardDrive, Menu, Monitor, MousePointer2,
  Network, Palette, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, PenTool, PenLine, Pencil, Highlighter, Eraser, Lasso, Hand, Pin, Plus, Puzzle,
  Redo2, RefreshCw, RotateCcw, Save, ScrollText, Search,
  Send, Server, Settings, Settings2, Share2, ShieldCheck, Smartphone, SquareKanban,
  StickyNote, Store, Tag, Trash2, Type, Undo2, Unlink,
  Users, WifiOff, X, Zap,
} from 'lucide-react'
import type { IconPack } from './tokens'

export const builtinPack: IconPack = {
  'alert-triangle':  AlertTriangle,
  'arrow-left':      ArrowLeft,
  'arrow-right':     ArrowRight,
  'arrow-up-right':  ArrowUpRight,
  'bar-chart-2':     BarChart2,
  'bold':            Bold,
  'book-open':       BookOpen,
  'bookmark':        Bookmark,
  'brackets':        Brackets,
  'heading-1':       Heading1,
  'heading-2':       Heading2,
  'italic':          Italic,
  'list-checks':     ListChecks,
  'list-ordered':    ListOrdered,
  'quote':           Quote,
  'strikethrough':   Strikethrough,
  'brain-circuit':   BrainCircuit,
  'bug':             Bug,
  'calendar':        Calendar,
  'calendar-days':   CalendarDays,
  'check':           Check,
  'check-circle-2':  CheckCircle2,
  'check-square':    CheckSquare,
  'chevron-down':    ChevronDown,
  'chevron-left':    ChevronLeft,
  'chevron-right':   ChevronRight,
  'chevron-up':      ChevronUp,
  'circle':          Circle,
  'clipboard-copy':  ClipboardCopy,
  'columns-2':       Columns2,
  'cloud':           Cloud,
  'cloud-off':       CloudOff,
  'code-2':          Code2,
  'copy':            Copy,
  'corner-down-left': CornerDownLeft,
  'crosshair':       Crosshair,
  'download':        Download,
  'external-link':   ExternalLink,
  'eye':             Eye,
  'file-down':       FileDown,
  'file-json':       FileJson,
  'file-text':       FileText,
  'flask-conical':   FlaskConical,
  'folder':          Folder,
  'folder-input':    FolderInput,
  'folder-open':     FolderOpen,
  'folder-plus':     FolderPlus,
  'folder-sync':     FolderSync,
  'git-fork':        GitFork,
  'git-merge':       GitMerge,
  'globe':           Globe,
  'graduation-cap':  GraduationCap,
  'grip-vertical':   GripVertical,
  'hash':            Hash,
  'history':         History,
  'home':            Home,
  'image':           Image,
  'film':            Film,
  'music':           Music,
  'paperclip':       Paperclip,
  'info':            Info,
  'keyboard':        Keyboard,
  'layers':             Layers,
  'layout-dashboard':   LayoutDashboard,
  'layout-list':        LayoutList,
  'lightbulb':       Lightbulb,
  'link':            Link,
  'link-2':          Link2,
  'list':            List,
  'loader-2':        Loader2,
  'lock':            Lock,
  'lock-open':       LockOpen,
  'more-horizontal': MoreHorizontal,
  'hard-drive':      HardDrive,
  'menu':            Menu,
  'monitor':         Monitor,
  'mouse-pointer-2': MousePointer2,
  'network':         Network,
  'palette':            Palette,
  'panel-left-close':   PanelLeftClose,
  'panel-left-open':    PanelLeftOpen,
  'panel-right-close':  PanelRightClose,
  'panel-right-open':   PanelRightOpen,
  'pen-tool':           PenTool,
  'pen-line':           PenLine,
  'pencil':             Pencil,
  'highlighter':        Highlighter,
  'eraser':             Eraser,
  'lasso':              Lasso,
  'hand':               Hand,
  'pin':             Pin,
  'plus':            Plus,
  'puzzle':          Puzzle,
  'redo-2':          Redo2,
  'refresh-cw':      RefreshCw,
  'rotate-ccw':      RotateCcw,
  'save':            Save,
  'scroll-text':     ScrollText,
  'search':          Search,
  'send':            Send,
  'server':          Server,
  'share':           Share2,
  'smartphone':      Smartphone,
  'settings':        Settings,
  'settings-2':      Settings2,
  'shield-check':    ShieldCheck,
  'square-kanban':   SquareKanban,
  'sticky-note':     StickyNote,
  'store':           Store,
  'tag':             Tag,
  'trash-2':         Trash2,
  'type':            Type,
  'undo-2':          Undo2,
  'unlink':          Unlink,
  'users':           Users,
  'wifi-off':        WifiOff,
  'x':               X,
  'zap':             Zap,
}
