export { timeAgo } from './timeAgo'
export { stripMarkdown } from './stripMarkdown'
export { colorForIndex } from './colorForIndex'
export { embedText, embedNote } from './embeddingClient'
export { parseWikilinks, parseTags } from './wikilinks'
export { cosineSimilarity, topKSimilar } from './similarity'
export { isDesktop, isMobile, getPlatform } from './platform'
export type { Platform } from './platform'
