//! Runs the real model. Opt-in (it needs a GGUF file):
//!   KAIROS_TEST_MODEL=path/to/model.gguf KAIROS_TEST_GRAMMARS=dir-with-intent.gbnf-and-tools.gbnf \
//!   cargo test --release --features local-llm local_llm -- --ignored --nocapture
use super::*;
use std::time::Instant;

fn run(backend: &LlamaBackend, model: &LlamaModel, req: GenerateRequest) -> (String, Option<f64>, f64, u32) {
    let started = Instant::now();
    let first = Mutex::new(None::<f64>);
    let out = Mutex::new(String::new());
    let done = Mutex::new(0u32);
    let abort = AtomicBool::new(false);
    generate(backend, model, 4096, &req, &|e| match e {
        TokenEvent::Token { text } => {
            first.lock().unwrap().get_or_insert(started.elapsed().as_secs_f64());
            out.lock().unwrap().push_str(&text);
        }
        TokenEvent::Done { completion_tokens, .. } => *done.lock().unwrap() = completion_tokens,
        TokenEvent::Error { message } => panic!("{message}"),
    }, &abort).unwrap();
    let total = started.elapsed().as_secs_f64();
    let text = out.into_inner().unwrap();
    (text, first.into_inner().unwrap(), total, done.into_inner().unwrap())
}

fn msg(role: &str, content: &str) -> ChatMessage {
    ChatMessage { role: role.into(), content: content.into() }
}

#[test]
#[ignore = "needs a GGUF model (KAIROS_TEST_MODEL)"]
fn runs_the_model_streaming_and_grammar_constrained() {
    let path = std::env::var("KAIROS_TEST_MODEL").expect("KAIROS_TEST_MODEL");
    let grammars = std::env::var("KAIROS_TEST_GRAMMARS").expect("KAIROS_TEST_GRAMMARS");
    let mut backend = LlamaBackend::init().unwrap();
    backend.void_logs();
    let t0 = Instant::now();
    let model = LlamaModel::load_from_file(&backend, &path, &LlamaModelParams::default()).unwrap();
    println!("load: {:.2}s", t0.elapsed().as_secs_f64());

    // Plain streaming answer.
    let (text, first, total, n) = run(&backend, &model, GenerateRequest {
        messages: vec![msg("system", "You are a concise assistant."), msg("user", "Name three uses of a kanban board, one line each.")],
        max_tokens: 120, temperature: 0.3, stop: vec![], grammar: None, thinking: false,
    });
    println!("plain: first token {:.2}s, {n} tokens in {total:.2}s = {:.1} tok/s\n{text}", first.unwrap_or(0.0), n as f64 / (total - first.unwrap_or(0.0)).max(0.001));
    assert!(n > 0 && !text.trim().is_empty());

    // JSON under the router's grammar (generated by src/ai/onDevice/gbnf.ts).
    let intent = std::fs::read_to_string(format!("{grammars}/intent.gbnf")).unwrap();
    let (json, _, _, _) = run(&backend, &model, GenerateRequest {
        messages: vec![msg("system", "Classify the message. Intents: pending, review, query, change, chitchat. Reply with JSON."), msg("user", "Move KAI-4 to Done")],
        max_tokens: 60, temperature: 0.0, stop: vec![], grammar: Some(intent), thinking: false,
    });
    println!("intent JSON: {json}");
    let v: serde_json::Value = serde_json::from_str(json.trim()).expect("grammar output is JSON");
    assert!(["pending", "review", "query", "change", "chitchat"].contains(&v["intent"].as_str().unwrap()));

    // Tool calls in the validated-JSON form under the tools grammar.
    let tools = std::fs::read_to_string(format!("{grammars}/tools.gbnf")).unwrap();
    let (calls, _, _, _) = run(&backend, &model, GenerateRequest {
        messages: vec![
            msg("system", "Propose board changes as JSON: {\"tool_calls\":[{\"name\":\"move_card\",\"arguments\":{\"cardId\":\"…\",\"toColumn\":\"…\"}}]}. Tools: create_card(column,title), update_card(cardId,…), move_card(cardId,toColumn)."),
            msg("user", "Move KAI-4 to Done"),
        ],
        max_tokens: 120, temperature: 0.0, stop: vec![], grammar: Some(tools), thinking: false,
    });
    println!("tool calls: {calls}");
    let v: serde_json::Value = serde_json::from_str(calls.trim()).expect("grammar output is JSON");
    assert!(v["tool_calls"].is_array());
}

/// Debug aid: runs messages from a JSON file and prints the prompt the template produced.
///   KAIROS_TEST_MODEL=… KAIROS_TEST_MESSAGES=messages.json cargo test --features local-llm \
///   local_llm::tests::runs_messages_file -- --ignored --nocapture
#[test]
#[ignore = "needs a GGUF model and a messages file"]
fn runs_messages_file() {
    let path = std::env::var("KAIROS_TEST_MODEL").expect("KAIROS_TEST_MODEL");
    let file = std::env::var("KAIROS_TEST_MESSAGES").expect("KAIROS_TEST_MESSAGES");
    let raw: Vec<serde_json::Value> = serde_json::from_str(&std::fs::read_to_string(file).unwrap()).unwrap();
    let messages: Vec<ChatMessage> = raw.iter().map(|m| msg(m["role"].as_str().unwrap(), m["content"].as_str().unwrap())).collect();
    let mut backend = LlamaBackend::init().unwrap();
    backend.void_logs();
    let model = LlamaModel::load_from_file(&backend, &path, &LlamaModelParams::default()).unwrap();
    let prompt = prompt_for(&model, &messages, false).unwrap();
    let vocab = model.vocab();
    let tokens = prompt_tokens(&model, &prompt);
    println!("should_add_bos={} bos={:?} first tokens={:?}", vocab.should_add_bos(), String::from_utf8_lossy(&vocab.token_to_piece(vocab.bos(), true, None)), &tokens[..tokens.len().min(5)]);
    println!("--- prompt ({} tokens) ---\n{}\n--- end prompt ---", tokens.len(), &prompt[prompt.len().saturating_sub(400)..]);
    let thinking = std::env::var("KAIROS_TEST_THINKING").is_ok();
    let (text, first, total, n) = run(&backend, &model, GenerateRequest {
        messages, max_tokens: 300, temperature: 0.3, stop: vec![], grammar: None, thinking,
    });
    println!("first {:.2}s, {n} tokens in {total:.2}s\n{text}", first.unwrap_or(0.0));
}
